# FROM python:3.9

# EXPOSE 8080

# CMD ["python", "app.py"]

FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt
# --no-cache-dir 

COPY . .

EXPOSE 5000

CMD [ "python", "app.py" ]

